project:
  type: website
  output-dir: docs

website:
  title: "NBA Shot Selection Analysis Over 15 Years"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: getting-started.html
        text: Getting Started
      - href: documentation.html
        text: Documentation
      - href: technical.html
        text: Technical Report

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true